# Database credentials secret
apiVersion: cutepod.io/v1
kind: CuteSecret
metadata:
  name: {{ .Values.secrets.database.name }}
  labels:
    app: {{ .Values.app.name }}
    component: database
    type: credentials
spec:
  type: generic
  data:
    username: {{ .Values.database.user | b64enc }}
    password: {{ .Values.database.password | b64enc }}
    database: {{ .Values.database.database | b64enc }}
    connection-string: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.database.user .Values.database.password .Values.database.name .Values.database.port .Values.database.database | b64enc }}

---
# API keys and configuration secret
apiVersion: cutepod.io/v1
kind: CuteSecret
metadata:
  name: {{ .Values.secrets.api.name }}
  labels:
    app: {{ .Values.app.name }}
    component: api
    type: configuration
spec:
  type: generic
  data:
    api-key: {{ "demo-api-key-12345" | b64enc }}
    jwt-secret: {{ "super-secret-jwt-key-for-demo" | b64enc }}
    redis-url: {{ printf "redis://%s:%d" .Values.cache.name .Values.cache.port | b64enc }}
    database-url: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.database.user .Values.database.password .Values.database.name .Values.database.port .Values.database.database | b64enc }}

---
# TLS certificates secret
apiVersion: cutepod.io/v1
kind: CuteSecret
metadata:
  name: {{ .Values.secrets.tls.name }}
  labels:
    app: {{ .Values.app.name }}
    component: tls
    type: certificate
spec:
  type: tls
  data:
    # Demo self-signed certificate (base64 encoded)
    tls.crt: {{ "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQU1CdFlYUXhZbTVoTUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFUE1BMEdBMVVFQnd3R1UyRnVJRVp5TUE4d0RRWURWUVFLREFaRQpaVzF2SUVOQk1ROHdEUVlEVlFRRERBWkVaVzF2SUVOQk1CNFhEVEl6TURrd01qRXdNREF3TUZvWERUSTBNRGt3Ck1qRXdNREF3TUZvd1JqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1ROHdEUVlEVlFRSERBWlQKWVc0Z1JuSXdEekFOQmdOVkJBb01Ca1JsYlc4Z1EwRXhEekFOQmdOVkJBTU1Ca1JsYlc4Z1EwRXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERoVGhOcjBBdmJHVnNiRzlYYjNKc1pDNWpiMjBnCmFYTWdZU0JrWlcxdklHTmxjblJwWm1sallYUmxJR1p2Y2lCa1pXMXZJSEIxY25CdmMyVnpJRzl1YkhrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t" | b64enc }}
    tls.key: {{ "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRERoVGhOcjBBdmJHVnMKYkc5WGIzSnNaQzVqYjIwZ2FYTWdZU0JrWlcxdklHTmxjblJwWm1sallYUmxJR1p2Y2lCa1pXMXZJSEIxY25CdgpjMlZ6SUc5dWJIaz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==" | b64enc }}