# Database persistent volume
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.database.name }}
  labels:
    app: {{ .Values.app.name }}
    component: database
    type: persistent
spec:
  driver: local
  options:
    type: none
    o: bind
  labels:
    usage: database-storage
    backup: required

---
# Web application content volume (bind mount)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.webapp.name }}
  labels:
    app: {{ .Values.app.name }}
    component: webapp
    type: bind-mount
spec:
  options:
    o: rw
  labels:
    usage: webapp-content
    backup: optional

---
# Application logs volume (bind mount)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.logs.name }}
  labels:
    app: {{ .Values.app.name }}
    component: logging
    type: bind-mount
spec:
  options:
    o: rw
  labels:
    usage: application-logs
    backup: required