# Database persistent volume (Named Podman volume)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.database.name }}
  labels:
    app: {{ .Values.app.name }}
    component: database
    type: persistent
spec:
  type: volume
  volume:
    driver: local
    options:
      type: none
      o: bind
  securityContext:
    owner:
      user: 999  # postgres user
      group: 999 # postgres group
    seLinuxOptions:
      level: private  # Private access for database

---
# Web application content volume (hostPath with subPath support)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.webapp.name }}
  labels:
    app: {{ .Values.app.name }}
    component: webapp
    type: bind-mount
spec:
  type: hostPath
  hostPath:
    path: {{ .Values.volumes.webapp.hostPath }}
    type: DirectoryOrCreate
  securityContext:
    owner:
      user: 101  # nginx user
      group: 101 # nginx group
    seLinuxOptions:
      level: shared  # Shared access for multiple webapp instances

---
# Application logs volume (hostPath with proper permissions)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.logs.name }}
  labels:
    app: {{ .Values.app.name }}
    component: logging
    type: bind-mount
spec:
  type: hostPath
  hostPath:
    path: {{ .Values.volumes.logs.hostPath }}
    type: DirectoryOrCreate
  securityContext:
    owner:
      user: 1000  # Common user for API service
      group: 1000 # Common group for API service
    seLinuxOptions:
      level: shared  # Shared access for multiple services

---
# Temporary cache volume (emptyDir for Redis)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.cache.name }}
  labels:
    app: {{ .Values.app.name }}
    component: cache
    type: temporary
spec:
  type: emptyDir
  emptyDir:
    medium: Memory  # Use tmpfs for better performance
    sizeLimit: {{ .Values.volumes.cache.sizeLimit }}
  securityContext:
    owner:
      user: 999  # redis user
      group: 999 # redis group

---
# Configuration volume (hostPath for config files)
apiVersion: cutepod.io/v1
kind: CuteVolume
metadata:
  name: {{ .Values.volumes.config.name }}
  labels:
    app: {{ .Values.app.name }}
    component: config
    type: configuration
spec:
  type: hostPath
  hostPath:
    path: {{ .Values.volumes.config.hostPath }}
    type: DirectoryOrCreate
  securityContext:
    owner:
      user: 0    # root for config files
      group: 0   # root group
    seLinuxOptions:
      level: shared  # Shared access for reading configs