# e2e/Containerfile
FROM docker.io/library/golang:1.24-alpine AS build

WORKDIR /app
COPY server/main.go .
RUN go build -o server main.go

FROM alpine
WORKDIR /app
COPY --from=build /app/server .
CMD ["./server"]
