---
kind: CuteContainer
apiVersion: cutepod/v1alpha0
metadata:
  name: {{ .Release.Name }}-container-2
spec:
  image: docker.io/strm/helloworld-http
  ports:
    - containerPort: 80
      hostPort: 18081