---
kind: CuteContainer
apiVersion: cutepod/v1alpha0
metadata:
  name: {{ .Release.Name }}-container
  namespace: {{ .Release.Namespace }}
spec:
  image: docker.io/strm/helloworld-http
  ports:
    - containerPort: 80
      hostPort: 18080