---
kind: CuteContainer
apiVersion: cutepod/v1alpha0
metadata:
  name: {{ .Release.Name }}-container
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image }}
  ports:
    - containerPort: 8080
      hostPort: 18080
  env:
    - name: MESSAGE
      value: Hello, world!