name: Podman CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      options: --privileged
      image: quay.io/podman/stable  # Official Podman image based on Fedora
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        run: |
          dnf install -y golang make gpgme-devel btrfs-progs-devel

      - name: Build CLI
        run: go build -o cute main.go

      - name: Run E2E tests
        run: |
          podman system service -t 0 &
          PODMAN_SOCK=unix://run/podman/podman.sock make e2e
